[package]
name = "allegro-reth"
description = "Reth integration for Allegro consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
allegro-consensus = { path = "../consensus" }

# Alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
